model:
    name: charge_model
    enforce_zero_for_disconnected_probes: True
    enforce_charge_conservation: True
    freeze_atomic: False
    
    atom_model_config:
        name: schnet_charge
        num_interactions: 6
        hidden_channels: 256
        cutoff: 6
        
    probe_model_config:
        name: schnet_charge
        num_interactions: 6
        hidden_channels: 256
        cutoff: 6
        
    otf_pga_config:
        num_probes: 50000
        cutoff: 6