optim:
    optimizer: Adam
    num_workers: 6
    lr_initial: 0.00001
    scheduler: ReduceLROnPlateau
    mode: min
    factor: 0.97
    patience: 1
    max_epochs: 1000
    loss_charge: normed_mae
    load_balancing: False
    eval_every: 100000
